// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"serenity-book-api/internal/handler"
	"serenity-book-api/internal/repository"
	"serenity-book-api/internal/security"
	"serenity-book-api/internal/server"
	"serenity-book-api/internal/service"
	"serenity-book-api/pkg/log"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger)
	db := repository.NewDb()
	client := repository.NewRedis()
	repositoryRepository := repository.NewRepository(logger, db, client)
	securityUtils := security.NewSecurityUtils(serviceService, repositoryRepository)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, securityUtils, userService)
	systemRepository := repository.NewSystemRepository(repositoryRepository)
	systemService := service.NewSystemService(serviceService, systemRepository)
	systemHandler := handler.NewSystemHandler(handlerHandler, systemService)
	engine := server.NewServerHTTP(logger, userHandler, systemHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var RepositorySet = wire.NewSet(repository.NewDb, repository.NewRedis, repository.NewRepository, repository.NewUserRepository, repository.NewSystemRepository)

var SecuritySet = wire.NewSet(security.NewSecurityUtils)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewSystemService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewSystemHandler)
